[workspace.package]
edition = "2024"
rust-version = "1.95"
license = "AGPL-3.0"

[workspace]
members = [
    "delulu-apps/*",
    "delulu-internals/rate-limited-crawler",
    "delulu-internals/mcp-server-helper",
    "delulu-internals/paper-search-test-utils",
]
resolver = "2"

[profile.release]
lto = "thin"
