// This file is @generated by prost-build.
/// ProtoHotelSearch - Top-level container sent to Google Hotels
/// Contains complete search configuration including guests, location,
/// dates, and filters.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProtoHotelSearch {
    #[prost(int32, tag = "1")]
    pub version: i32,
    #[prost(message, optional, tag = "2")]
    pub guests: ::core::option::Option<Guests>,
    #[prost(message, optional, tag = "3")]
    pub search_params: ::core::option::Option<SearchParams>,
    #[prost(message, optional, tag = "5")]
    pub filter_config: ::core::option::Option<FilterConfig>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Guests {
    #[prost(message, repeated, tag = "1")]
    pub entries: ::prost::alloc::vec::Vec<GuestEntry>,
    #[prost(bool, tag = "2")]
    pub explicit_selection: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GuestEntry {
    #[prost(enumeration = "GuestKind", tag = "1")]
    pub kind: i32,
    #[prost(int32, tag = "2")]
    pub age: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchParams {
    #[prost(message, optional, tag = "1")]
    pub location: ::core::option::Option<LocationData>,
    #[prost(message, optional, tag = "2")]
    pub dates: ::core::option::Option<DateWrapper>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LocationData {
    #[prost(message, optional, tag = "2")]
    pub details: ::core::option::Option<LocationDetails>,
    #[prost(message, optional, tag = "3")]
    pub marker: ::core::option::Option<UnknownMessage>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LocationDetails {
    #[prost(string, tag = "1")]
    pub location_id: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub coordinates: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub display_name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UnknownMessage {
    #[prost(int32, tag = "1")]
    pub flags: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DateWrapper {
    #[prost(message, optional, tag = "2")]
    pub date_range: ::core::option::Option<DateRange>,
    #[prost(message, optional, tag = "6")]
    pub flags: ::core::option::Option<UnknownMessage>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DateRange {
    #[prost(message, optional, tag = "1")]
    pub checkin: ::core::option::Option<DateDetails>,
    #[prost(message, optional, tag = "2")]
    pub checkout: ::core::option::Option<DateDetails>,
    #[prost(int32, tag = "3")]
    pub nights: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DateDetails {
    #[prost(int32, tag = "1")]
    pub year: i32,
    #[prost(int32, tag = "2")]
    pub month: i32,
    #[prost(int32, tag = "3")]
    pub day: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FilterConfig {
    #[prost(message, optional, tag = "1")]
    pub filters: ::core::option::Option<FilterData>,
    #[prost(message, optional, tag = "3")]
    pub padding: ::core::option::Option<UnknownMessage>,
    #[prost(message, optional, tag = "4")]
    pub price_data: ::core::option::Option<PriceData>,
    #[prost(int32, tag = "5")]
    pub guest_rating: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FilterData {
    #[prost(enumeration = "Amenity", repeated, tag = "1")]
    pub amenity: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, tag = "2")]
    pub stars: ::prost::alloc::vec::Vec<i32>,
    #[prost(message, optional, tag = "3")]
    pub padding: ::core::option::Option<UnknownMessage>,
    #[prost(enumeration = "SortType", tag = "5")]
    pub sort_type: i32,
    #[prost(string, tag = "7")]
    pub currency: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PriceData {
    #[prost(message, optional, tag = "1")]
    pub min_price: ::core::option::Option<PriceValue>,
    #[prost(message, optional, tag = "2")]
    pub max_price: ::core::option::Option<PriceValue>,
    #[prost(int32, tag = "3")]
    pub unknown_price_marker: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PriceValue {
    #[prost(int32, tag = "2")]
    pub value: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum GuestKind {
    Unspecified = 0,
    Child = 2,
    Adult = 3,
}
impl GuestKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "GUEST_KIND_UNSPECIFIED",
            Self::Child => "CHILD",
            Self::Adult => "ADULT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "GUEST_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "CHILD" => Some(Self::Child),
            "ADULT" => Some(Self::Adult),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SortType {
    Relevance = 0,
    LowestPrice = 3,
    HighestRating = 8,
    MostReviewed = 13,
}
impl SortType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Relevance => "RELEVANCE",
            Self::LowestPrice => "LOWEST_PRICE",
            Self::HighestRating => "HIGHEST_RATING",
            Self::MostReviewed => "MOST_REVIEWED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "RELEVANCE" => Some(Self::Relevance),
            "LOWEST_PRICE" => Some(Self::LowestPrice),
            "HIGHEST_RATING" => Some(Self::HighestRating),
            "MOST_REVIEWED" => Some(Self::MostReviewed),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Amenity {
    Unspecified = 0,
    IndoorPool = 4,
    OutdoorPool = 5,
    Pool = 6,
    Spa = 10,
    KidFriendly = 12,
    AirConditioned = 40,
    EvCharger = 61,
}
impl Amenity {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "AMENITY_UNSPECIFIED",
            Self::IndoorPool => "INDOOR_POOL",
            Self::OutdoorPool => "OUTDOOR_POOL",
            Self::Pool => "POOL",
            Self::Spa => "SPA",
            Self::KidFriendly => "KID_FRIENDLY",
            Self::AirConditioned => "AIR_CONDITIONED",
            Self::EvCharger => "EV_CHARGER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AMENITY_UNSPECIFIED" => Some(Self::Unspecified),
            "INDOOR_POOL" => Some(Self::IndoorPool),
            "OUTDOOR_POOL" => Some(Self::OutdoorPool),
            "POOL" => Some(Self::Pool),
            "SPA" => Some(Self::Spa),
            "KID_FRIENDLY" => Some(Self::KidFriendly),
            "AIR_CONDITIONED" => Some(Self::AirConditioned),
            "EV_CHARGER" => Some(Self::EvCharger),
            _ => None,
        }
    }
}
