use super::*;
use crate::pipelines::DomNode;
use crate::pipelines::parse_html;

/// Helper: create a simple document with text content
fn make_doc(text_len: usize) -> DomNode {
    let text = "x".repeat(text_len);
    DomNode::Element {
        tag: "html".to_string(),
        attrs: vec![],
        children: vec![DomNode::Element {
            tag: "body".to_string(),
            attrs: vec![],
            children: vec![DomNode::Text(text)],
            scores: std::collections::HashMap::new(),
            metadata: std::collections::HashMap::new(),
        }],
        scores: std::collections::HashMap::new(),
        metadata: std::collections::HashMap::new(),
    }
}

/// A pass that removes ALL text content (simulates aggressive removal)
fn remove_all_text(node: &mut DomNode) {
    if let DomNode::Element { children, .. } = node {
        children.clear();
        children.push(DomNode::new_element("p"));
    }
}

/// A pass that removes NO text content (simulates safe pass)
fn noop_pass(_node: &mut DomNode) {}

/// Recovery: full restore
fn full_restore(node: &mut DomNode, backup: &DomNode) {
    *node = backup.clone();
}

#[test]
fn test_with_backup_threshold_triggered() {
    // 5x threshold: if new_len * 5 <= old_len, restore
    // old_len = 100, new_len = 10, threshold = 5
    // 10 * 5 = 50 <= 100 -> triggered
    let mut doc = make_doc(100);
    with_backup(&mut doc, remove_all_text, 5, full_restore);
    // Should be restored to original (backup)
    assert_eq!(
        doc.text_len(),
        100,
        "should be restored when threshold triggered"
    );
}

#[test]
fn test_with_backup_threshold_not_triggered() {
    // old_len = 100 -> new_len = 60; 60 * 5 = 300 > 100 -> NOT restored
    let restored = std::cell::Cell::new(false);
    let mut doc = make_doc(100);
    with_backup(
        &mut doc,
        |n| *n = make_doc(60),
        5,
        |_, _| restored.set(true),
    );
    assert!(
        !restored.get(),
        "recovery must NOT run when new_len*threshold > old_len"
    );
    assert_eq!(doc.text_len(), 60, "modified tree must be kept");
}

#[test]
fn test_with_backup_overflow_safe() {
    // new_len=10, threshold=usize::MAX -> 10 * MAX overflows usize ->
    // checked_mul returns None -> keep modified tree (no restore, no panic)
    let restored = std::cell::Cell::new(false);
    let mut doc = make_doc(10);
    with_backup(&mut doc, noop_pass, usize::MAX, |_, _| restored.set(true));
    assert!(
        !restored.get(),
        "overflow must keep modified tree (no restore)"
    );
    assert_eq!(doc.text_len(), 10, "tree unchanged on overflow");
}

#[test]
fn test_with_backup_zero_threshold() {
    // threshold = 0: new_len * 0 = 0 <= old_len always -> always restore
    let restored = std::cell::Cell::new(false);
    let mut doc = make_doc(100);
    with_backup(
        &mut doc,
        |n| *n = make_doc(10),
        0,
        |node, backup| {
            *node = backup.clone();
            restored.set(true);
        },
    );
    assert!(restored.get(), "zero threshold must always restore");
    assert_eq!(doc.text_len(), 100, "tree restored to original length");
}

#[test]
fn test_backup_restore_does_not_reintroduce_cleaned_tags() {
    // Regression: backup restore must not re-introduce cleaned tags.
    // Build a doc with <script>, <aside> (cleaned tags) and <p> (content).
    // Include lots of cleaned content so the cleaning pass removes >=80% of
    // the text, forcing with_backup's 5x threshold to trigger a restore.
    let html = "<html><body><script>alert(1)alert(2)alert(3)alert(4)alert(5)alert(6)</script><aside>sidebar one two three four five six</aside><p>main content here</p></body></html>";
    let mut doc = parse_html(html).unwrap();

    // The production cleaning pass: walk + tf_remove_cleaned.
    let cleaning_pass = |n: &mut DomNode| walk_pre_mut(n, &|n| tf_remove_cleaned(n));

    // Sanity: cleaning alone removes the cleaned tags but keeps content.
    let mut cleaned = doc.clone();
    cleaning_pass(&mut cleaned);
    assert!(
        !cleaned.text_content().contains("sidebar"),
        "<aside> should be removed by tf_remove_cleaned"
    );
    assert!(
        !cleaned.text_content().contains("alert"),
        "<script> should be removed by tf_remove_cleaned"
    );
    assert!(
        cleaned.text_content().contains("main content here"),
        "content should survive cleaning"
    );

    // Exercise the REAL production helper `with_backup` with the production
    // recovery closure (full restore + re-clean), exactly as generated by
    // `with_backup_wrapper!`. The pass removes >=80% of the text, so the
    // threshold triggers and recovery restores the UNCLEANED backup and
    // re-applies tf_remove_cleaned.
    with_backup(&mut doc, cleaning_pass, 5, |node, backup| {
        *node = backup.clone();
        walk_pre_mut(node, &|n| tf_remove_cleaned(n));
    });

    // After restore + re-clean, cleaned tags must still be gone,
    // and content must survive.
    assert!(
        !doc.text_content().contains("sidebar"),
        "cleaned tags must not reappear after restore"
    );
    assert!(
        !doc.text_content().contains("alert"),
        "script must not reappear after restore"
    );
    assert!(
        doc.text_content().contains("main content here"),
        "content should be preserved"
    );
}

// ── Anti-regression: JSON-LD error logging ─────────────────────

#[test]
fn test_extract_jsonld_malformed_json_returns_none() {
    // Issue 1 regression: malformed JSON-LD should not panic,
    // should return None gracefully, and should log a warning.
    // Build a DOM tree with a malformed JSON-LD script element.
    let malformed_json = r#"{invalid json here"#;
    let html = format!(
        r#"<html><body><script type="application/ld+json">{}</script></body></html>"#,
        malformed_json
    );
    let root = parse_html(&html).unwrap();
    let result = crate::pipelines::passes::tf_analysis::extract_jsonld_article_body(&root);
    assert!(
        result.is_none(),
        "malformed JSON-LD should return None (not panic)"
    );
}

// ── Anti-regression: recovery dedup with HashSet ────────────────

#[test]
fn test_recover_wild_paragraphs_substring_not_dedupped() {
    // Issue 3 regression: paragraph 'A' exists, 'A B' is recovered.
    // Both should be kept (substring match must not cause false dedup).
    // Build best_tree with only <p>A</p>
    let mut best_tree = DomNode::Element {
        tag: "html".to_string(),
        attrs: vec![],
        children: vec![DomNode::Element {
            tag: "body".to_string(),
            attrs: vec![],
            children: vec![DomNode::Element {
                tag: "p".to_string(),
                attrs: vec![],
                children: vec![DomNode::Text("A".to_string())],
                scores: std::collections::HashMap::new(),
                metadata: std::collections::HashMap::new(),
            }],
            scores: std::collections::HashMap::new(),
            metadata: std::collections::HashMap::new(),
        }],
        scores: std::collections::HashMap::new(),
        metadata: std::collections::HashMap::new(),
    };

    // Build original with <p>A</p> and <p>A B</p>
    let original = DomNode::Element {
        tag: "html".to_string(),
        attrs: vec![],
        children: vec![DomNode::Element {
            tag: "body".to_string(),
            attrs: vec![],
            children: vec![
                DomNode::Element {
                    tag: "p".to_string(),
                    attrs: vec![],
                    children: vec![DomNode::Text("A".to_string())],
                    scores: std::collections::HashMap::new(),
                    metadata: std::collections::HashMap::new(),
                },
                DomNode::Element {
                    tag: "p".to_string(),
                    attrs: vec![],
                    children: vec![DomNode::Text("A B".to_string())],
                    scores: std::collections::HashMap::new(),
                    metadata: std::collections::HashMap::new(),
                },
            ],
            scores: std::collections::HashMap::new(),
            metadata: std::collections::HashMap::new(),
        }],
        scores: std::collections::HashMap::new(),
        metadata: std::collections::HashMap::new(),
    };

    let appended = super::recover_wild_paragraphs(&mut best_tree, &original, 0);
    let text = best_tree.text_content();
    assert!(
        text.contains("A B"),
        "'A B' should be recovered (not falsely dedupped by substring match)"
    );
    // A B was appended
    assert!(appended >= 1, "at least one paragraph should be appended");
}

#[test]
fn test_recover_wild_paragraphs_exact_duplicates_dedupped() {
    // Issue 3 regression: exact same paragraph appears twice.
    // Should only be added once.
    let mut best_tree = DomNode::Element {
        tag: "html".to_string(),
        attrs: vec![],
        children: vec![DomNode::Element {
            tag: "body".to_string(),
            attrs: vec![],
            children: vec![DomNode::Element {
                tag: "p".to_string(),
                attrs: vec![],
                children: vec![DomNode::Text("hello".to_string())],
                scores: std::collections::HashMap::new(),
                metadata: std::collections::HashMap::new(),
            }],
            scores: std::collections::HashMap::new(),
            metadata: std::collections::HashMap::new(),
        }],
        scores: std::collections::HashMap::new(),
        metadata: std::collections::HashMap::new(),
    };

    // Original has the same paragraph twice
    let original = DomNode::Element {
        tag: "html".to_string(),
        attrs: vec![],
        children: vec![DomNode::Element {
            tag: "body".to_string(),
            attrs: vec![],
            children: vec![
                DomNode::Element {
                    tag: "p".to_string(),
                    attrs: vec![],
                    children: vec![DomNode::Text("hello".to_string())],
                    scores: std::collections::HashMap::new(),
                    metadata: std::collections::HashMap::new(),
                },
                DomNode::Element {
                    tag: "p".to_string(),
                    attrs: vec![],
                    children: vec![DomNode::Text("hello".to_string())],
                    scores: std::collections::HashMap::new(),
                    metadata: std::collections::HashMap::new(),
                },
            ],
            scores: std::collections::HashMap::new(),
            metadata: std::collections::HashMap::new(),
        }],
        scores: std::collections::HashMap::new(),
        metadata: std::collections::HashMap::new(),
    };

    let appended = super::recover_wild_paragraphs(&mut best_tree, &original, 0);
    // The duplicate 'hello' paragraph should NOT be appended (already in best_tree)
    // The second 'hello' paragraph is still in original but its text matches best_tree
    // So appended should be 0 (no new unique text)
    assert_eq!(appended, 0, "exact duplicate should not be appended");
}

// ── Fix 1: Last-resort fallback returns a CLEANED tree ────────────

#[test]
fn test_fallback_returns_cleaned_tree() {
    // A small doc whose cascade produces <500 chars triggers the last-resort
    // fallback. The fallback must return a CLEANED clone of the original tree,
    // i.e. <script>/<aside> text removed while <p> content is retained.
    let html = "<html><body><script>var x = 1;</script><aside>sidebar junk</aside><p>short content</p></body></html>";
    let mut doc = parse_html(html).unwrap();
    filter_trafilatura(&mut doc);
    let text = doc.text_content();
    assert!(
        !text.contains("var x = 1"),
        "fallback output must not contain <script> text"
    );
    assert!(
        !text.contains("sidebar junk"),
        "fallback output must not contain <aside> text"
    );
    assert!(
        text.contains("short content"),
        "fallback output must retain <p> content"
    );
}

// ── Fix 3: Recall all-<p> safety net ─────────────────────────────────

#[test]
fn test_recall_cleaning_preserves_all_p() {
    // A doc whose ONLY <p> lives inside a cleaned tag (<aside>). The recall
    // cleaning would remove <aside> (and with it the only <p>). The safety net
    // must restore a <p>-bearing tree rather than emptying it.
    let html = "<html><body><aside><p>only paragraph</p></aside></body></html>";
    let mut doc = parse_html(html).unwrap();
    super::apply_recall_with_p_guard(&mut doc);
    assert!(
        super::count_p_elements(&doc) > 0,
        "recall cleaning must not empty a tree whose only <p> is inside a cleaned tag"
    );
    assert!(
        doc.text_content().contains("only paragraph"),
        "the <p> content must be retained"
    );
}

// ── Issue C regression: recovered <p> must survive the full pipeline ──

/// Regression test for Issue C.
///
/// `tf_fallback_content_container` is a Rust-internal heuristic with NO Python
/// counterpart: Python's `_extract()` (trafilatura/main_extractor.py:597-608)
/// iterates BODY_XPATH once and extracts the FIRST matching subtree — it never
/// re-runs a "pick the best <p> child" pass after extraction.
///
/// In Rust the fallback legitimately runs inside the backup closure of
/// `apply_tf_isolate_container_with_backup`. But it must NOT appear as a
/// standalone pass in TF_BALANCED/TF_RECALL: when the container isolation
/// triggers backup recovery (`recover_wild_p_elements`), the tree regains
/// multiple top-level children, and a second standalone fallback re-isolates,
/// dropping the just-recovered <p> elements.
///
/// This test feeds a doc whose isolation step removes >=90% of text (so the
/// backup closure recovers wild <p>s back into a multi-child tree) and asserts
/// the recovered <p>s survive the entire TF_BALANCED pipeline.
#[test]
fn test_bal_pipeline_preserves_recovered_p_after_backup() {
    // article.post is the BODY_XPATH match (>=250 chars of <p> text).
    // The secondary div is large enough that isolating only the article
    // removes >=90% of total text, triggering the backup closure's
    // recover_wild_p_elements, which pushes the div's two <p>s back as
    // top-level siblings -> a multi-child tree.
    let a = "ALPHABRAVO".repeat(30); // 300 chars in article.post
    let b = "CHARLIEDELTA".repeat(400); // 4800 chars, recovered wild <p>
    let c = "ECHOFOXTROT".repeat(300); // 3300 chars, recovered wild <p>
    let html = format!(
        "<html><body>\
         <article class=\"post\"><p>{a}</p></article>\
         <div class=\"secondary\"><p>{b}</p><p>{c}</p></div>\
         </body></html>"
    );
    let mut doc = parse_html(&html).unwrap();
    for pass in *super::TF_BALANCED {
        pass(&mut doc);
    }
    let text = doc.text_content();
    assert!(
        text.contains("CHARLIEDELTA"),
        "recovered <p> (CHARLIEDELTA) must survive the TF_BALANCED pipeline"
    );
    assert!(
        text.contains("ECHOFOXTROT"),
        "recovered <p> (ECHOFOXTROT) must survive the TF_BALANCED pipeline"
    );
}

/// Issue D: `TF_BALANCED_NAMES` must stay aligned index-for-index with
/// `TF_BALANCED` and contain no empty labels. If a pass is added/removed/renamed
/// in `TF_BALANCED` without updating `TF_BALANCED_NAMES`, this test fails, catching
/// the drift that used to silently mislabel the per-pass trace.
#[test]
fn test_tf_balanced_names_aligned_with_passes() {
    let passes = *super::TF_BALANCED;
    let names = *super::TF_BALANCED_NAMES;
    assert_eq!(
        names.len(),
        passes.len(),
        "TF_BALANCED_NAMES ({}) must have one entry per TF_BALANCED pass ({})",
        names.len(),
        passes.len(),
    );
    for (i, name) in names.iter().enumerate() {
        assert!(!name.is_empty(), "TF_BALANCED_NAMES[{i}] must be non-empty");
    }
}

// ── Issue W: macros must be path-hygienic ─────────────────────────────
//
// This nested module deliberately does NOT `use` (or inherit via the parent's
// `use super::*`) the unqualified names `walk_pre_mut`, `DomNode`, or
// `WalkerAction`. It only ever refers to them fully qualified as
// `crate::pipelines::...`. Before the `$crate::` hygiene fix, invoking
// `crate::wrap_pass!` / `crate::wrap_pass_void!` here failed to compile because
// their expansions referenced those names unqualified.
mod hygiene {
    fn pass(_n: &mut crate::pipelines::DomNode) -> crate::pipelines::WalkerAction {
        crate::pipelines::WalkerAction::Continue
    }

    fn void_pass(_n: &mut crate::pipelines::DomNode) {}

    #[test]
    fn macros_are_path_hygienic() {
        let _: fn(&mut crate::pipelines::DomNode) = crate::wrap_pass!(pass);
        let _: fn(&mut crate::pipelines::DomNode) = crate::wrap_pass_void!(void_pass);
    }
}
